config/routes.rb
StudentSite::Application.routes.draw do
  get "students/edit"

  get "students/show"

  get "students/index"

  get "students/new"

  resources :students

end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :name, :quote, :twitter, :linkedin, :github, :bio, :education, :work
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
 # GET /students
  # GET /students.json
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudentSite</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/edit.html.erb
<h1>Students#edit</h1>
<p>Find me in app/views/students/edit.html.erb</p>

app/views/students/index.html.erb
<h1>Listing Flatiron Students</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.name %></td>
    <td><%= student.quote %></td>
    <td><%= link_to 'Show', student %></td>
    <td><%= link_to 'Edit', edit_student_path(student) %></td>
    <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>Students#new</h1>
<p>Find me in app/views/students/new.html.erb</p>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>
<h1> <%= @student.name %> </h1>
<ul>
  <li> Quote: <%= @student.quote %> </li>
  <li> Bio: <%= @student.bio %> </li>
  <li> Twitter: <%= @student.twitter %> </li>
  <li> LinkedIn: <%= @student.linkedin %> </li>
  <li> GitHub: <%= @student.bio %> </li>
  <li> Education: <%= @student.twitter %> </li>
  <li> Work: <%= @student.work %> </li>
</ul>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>